name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: permission
        run: chmod +x cucumber-json-formatter 
      - name: dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
