name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: permission
        run: |
          mkdir -p cypress/config/cucumber_json
          echo "${{ github.workspace }}/cypress/config/cucumber_json" >> $GITHUB_PATH
          cd cypress/config/cucumber_json
          curl https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -o cucumber-json-formatter
          chmod +x cucumber-json-formatter
      - name: Test formatter
        run: cucumber-json-formatter --help 
      - name: dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Test results into artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: cypress/cucumberReports/
